# GitHub Actions (ci-cd.yml)
name: Java CI/CD with Advanced Automation

on:
  push:
    branches:
      - master

jobs:
  provision-infra:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      run: |
        sudo apt-get update && sudo apt-get install -y terraform
        terraform init
        terraform apply -auto-approve

  build:
    runs-on: ubuntu-latest
    needs: provision-infra
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn package -DskipTests

  parallel-tests:
    needs: build
    strategy:
      matrix:
        test-type: [unit-tests, static-analysis]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run Tests
      run: |
        if [ "${{ matrix.test-type }}" == "unit-tests" ]; then
          mvn test;
        elif [ "${{ matrix.test-type }}" == "static-analysis" ]; then
          mvn sonar:sonar;
        fi

  deploy:
    runs-on: ubuntu-latest
    needs: parallel-tests
    steps:
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl rollout status deployment/my-java-app

  monitor-and-scale:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Setup Auto-scaling
      run: |
        kubectl autoscale deployment my-java-app --cpu-percent=50 --min=2 --max=10
