# azure-pipelines.yml
trigger:
  branches:
    include:
      - master

stages:
- stage: ProvisionInfrastructure
  displayName: "Provision Infrastructure with IaC"
  jobs:
  - job: TerraformDeploy
    displayName: "Deploy Infrastructure with Terraform"
    steps:
    - task: UsePythonVersion@1
      inputs:
        versionSpec: '3.x'
    - script: |
        python -m pip install --upgrade pip
        pip install terraform
        terraform init
        terraform apply -auto-approve
      displayName: "Run Terraform"

- stage: Build
  displayName: "Build Application"
  dependsOn: ProvisionInfrastructure
  jobs:
  - job: BuildJob
    displayName: "Build Java App"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: "pom.xml"
        mavenOptions: "-Xmx1024m"
        javaHomeOption: "JDKVersion"
        jdkVersion: "11"
        goals: "package -DskipTests"

- stage: ParallelTesting
  displayName: "Run Tests in Parallel"
  dependsOn: Build
  jobs:
  - job: StaticAnalysis
    displayName: "Static Code Analysis"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: mvn sonar:sonar
      displayName: "Run SonarQube Analysis"

  - job: UnitTests
    displayName: "Unit Testing"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: mvn test
      displayName: "Run Unit Tests"

- stage: Deploy
  displayName: "Deploy to Kubernetes Cluster"
  dependsOn: ParallelTesting
  jobs:
  - job: DeployToK8s
    displayName: "Deploy App to Kubernetes"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        kubectl apply -f deployment.yaml
        kubectl rollout status deployment/my-java-app
      displayName: "Deploy to Kubernetes"

- stage: Monitor
  displayName: "Event-Driven Scaling"
  dependsOn: Deploy
  jobs:
  - job: ScaleOnTraffic
    displayName: "Scale Kubernetes Pods"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        kubectl autoscale deployment my-java-app --cpu-percent=50 --min=2 --max=10
      displayName: "Enable HPA"
